apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- patches/deployment.namespace.patch.yaml
- patches/ingress.staging.patch.yaml

namespace: staging