apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- issuer.yaml

patchesStrategicMerge:
- patches/deployment.rmv-debug.patch.yaml
- patches/ingress.add-tls.patch.yaml

namespace: production