apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poke-api-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: core/poke-api/overlays/staging
    repoURL: https://github.com/curioushuman/poke-k8s.git
    targetRevision: HEAD
    kustomize:
      # https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/
      images:
      - curioushuman/poke-api:1.1.4
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

