apiVersion: v2
name: poke-api
description: A Helm chart for the Poke-E-Dentifier API
type: application
version: 0.0.3
appVersion: "0.0.2"
dependencies:
  - name: poke-lib
    repository: "file://../poke-lib"
    version: ~0.0.2
    tags:
      - library
      - shared
  # https://artifacthub.io/packages/helm/bitnami/mongodb
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: ~11.1.10
    tags:
      - database
      - mongodb
