apiVersion: v2
name: poke-api
description: A Helm chart for the Poke-E-Dentifier API
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: poke-lib
    repository: "file://../poke-lib"
    version: ~0.0.1
    tags:
      - library
      - shared
