apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poke-certificate
  # Namespace will be added by ArgoCD
  # namespace: argocd
spec:
  dnsNames:
    - poke-api.curioushuman.com.au
  secretName: letsencrypt-poke-secret
  issuerRef:
    name: letsencrypt-poke
    kind: ClusterIssuer