apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- issuer.yaml
- poke-api-mongodb.prod.yaml

patchesStrategicMerge:
- patches/deployment.rmv-debug.patch.yaml
- patches/ingress.add-tls.patch.yaml
- patches/poke-api.mongodb.delete.yaml

replacements:
- path: patches/poke-api-mongodb.replacement.yaml

namespace: production